### ISSUE TITLE
Stuck on not able to connect, some error occured

### ISSUE THREAD

**Issue by rohitbegani** [raghav-grover/react-twilio#2]
Hi, thanks for creating this component. 

It seems like I'm not implementing this component correctly in my app but I'm not sure what I'm doing wrong. I followed the code given in the readme, the only difference is that I'm getting the access token and the room name from the backend. 

But the player always seems to get stuck on `Not able to connect, some error occurred`. I tried explicitly passing a token and in that case, it didn't show the same error message but it was stuck on the spinner. I guess in the second scenario it was stuck on the spinner because I didn't open it another window. Still not sure why making an API request and setting states isn't working.

**Comment by raghav-grover** [comment]
I hope you are using different auth token which is not used by any other
client to connect, and also make sure the roomName is in string, and is
consistent across all who are connecting to room.

So you should have two different tokens to connect to the room, lets just first try with explicitly passing the token, and then we can have a look at to why the other case is not working.
And if it is waiting on the spinner, that means it is waiting for some other client to connect on the same room but obviously with different auth token.

Let me know if you are aligned with this.

**Comment by rohitbegani** [comment]
So it waits on the spinner when I explicitly pass the access token in the code but it straight up shows the error on using `states`. This is how my react file looks like:

```
import React, { Component } from "react";
import API from "../../api";
import TwilioVideo from 'react-twilio';

class VideoConference extends Component{
    constructor(props){
        super(props);
        this.shadowStyle = {
            border: '1px solid #dcd9d9',
            borderRadius: '4px',
            marginBottom: '15px',
            boxShadow: '5px 5px 5px #e0e3e4',
            fontWeight: 'lighter'
        };
        this.state = {
            access_token: '',
            name: ''
        };
    }

    componentWillMount() {
        API.get("twilio/generate_access_token", {}, function (res) {
            this.setState({
                access_token: res.token,
                name: res.room_name
            });
        }.bind(this));
    }

    render() {
        return(
            <div style={{ height: '800px', width: '50%' }}>
                <TwilioVideo roomName={this.state.name.toString()} token={this.state.access_token.toString()} style={{ ...this.shadowStyle, boxShadow: '5px 5px 5px #e0e3e4' }} />
            </div>
        );
    }
}

export default VideoConference;
```

As you can see the only difference from the example is the API request. Is there something wrong in my implementation of the package?
I even explicitly converted my values to String to ensure type.

**Comment by raghav-grover** [comment]
Okay i think i got it.
For testing that can you please put a check that if the state.access_token
is null, then you don't render the Video component at all, you may just
return an empty div.

Could you please try as that well ? It should render only if you have a
valid access token.

**Comment by rohitbegani** [comment]
Okay, I understand your point so the component is getting loaded before it gets the access token. So I updated it as you suggested and it does reach the spinner now. Can't confirm if it connects perfectly yet since I need to look into a way to get multiple auth tokens because both the parties for these video calls are used to work on the same application and I have a common auth token for the application at the moment.

Edit: Actually a clarification, is different auth tokens a Twilio constraint or a component constraint?

**Comment by raghav-grover** [comment]
Sure do let me know :)

**Comment by rohitbegani** [comment]
Maybe you missed my last question because I added it as an edit to my message, but can you let me know if the requirement of unique auth_tokens is a Twilio constraint or a `react-twilio` constraint? 

Thank you for developing this component and for taking out the time to answer these questions.

**Comment by raghav-grover** [comment]
Its a Twilio constraint, no two same auth tokens can connect in a single
room. If you do this, the previous connected client will disconnect.

Please do star this repo, if it helps you in any way.

**Comment by rohitbegani** [comment]
Okay an update on this issue, so it does work now. For some reason, it needs a few reloads to get started. And turning off the video resets it back to the loading spinner. I'm going to work on debugging that now and post an update here if I manage to make it work in a consistent manner

**Comment by rohitbegani** [comment]
Closing this issue for now because my original problem was resolved.
